version: "3.5"

services:

    mysql-db:
      image: mysql:latest
      container_name: mysql-db
      command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      volumes:
              - ./db:/var/lib/mysql
              - ./conf/my.cnf:/etc/my.cnf
              - ./init:/docker-entrypoint-initdb.d/
      environment:
              - MYSQL_ROOT_PASSWORD=mycloud
              # - MYSQL_DATABASE=nextcloud
              - MYSQL_USER=nathan
              - MYSQL_PASSWORD=interboy
      restart: always